WIP dead end giving up .. read full details in full commit message
I'm giving up on this route and going back to original approach; because
ClassLoaders are a PITA... ;-) GeneratorsTest actually passes with this,
but org.eclipse.emf.eson.example causes a
java.lang.IllegalArgumentException: argument type mismatch at
org.eclipse.emf.eson.generators.DelegatingGenerator.doGenerateUsingReflection(DelegatingGenerator.java:81);
I don't really understand the difference.