[tests] Re-Export xtend.ide as transitive dependency (DS-8734), as this
avoids having to explicitly add org.eclipse.xtend.ide to test bundles in
other products which use ESON, causing a NoClassDefFoundError:
org/eclipse/xtend/ide/macro/JdtBasedProcessorProvider.

Change-Id: I71e1ba32c30978def87785a6c41924011b3be527